Revert "Comment out Kaminari pagination; it was causing this error: ActionView::Template::Error (undefined local variable or method 'prev_span_tag' for #<Kaminari::Helpers::Paginator:0x00000003387d60>) and crashing rails s"
This reverts commit 53231d72aba89d80e71c3c55c6a6c06e592e9260.